### ISSUE TITLE
 Fatal error: Class 'Zend\ServiceManager\AbstractPluginManager' not found in D:\XAMPP\htdocs\sn\zend-mail\vendor\zendframework\zend-mail\src\Protocol\SmtpPluginManager.php on line 20

### ISSUE THREAD

**Issue by sakinaaf** [zendframework/zend-inputfilter#186] opened 2019-08-01 17:18 UTC
Fatal error: Class 'Zend\ServiceManager\AbstractPluginManager' not found in D:\XAMPP\htdocs\sn\zend-mail\vendor\zendframework\zend-mail\src\Protocol\SmtpPluginManager.php on line 20

**Comment by froschdesign** [comment] 2019-08-01 19:07
Duplicate of zendframework/zend-mail#233

**Closed by froschdesign** 2019-08-01 19:07 UTC
